version = 1

test_patterns = [
    "/prisma/**",
    "/src/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  style_guide = "standard"
  dialect = "typescript"

[[analyzers]]
name = "sql"
enabled = true
