-- User --
DROP TABLE IF EXISTS "public"."User";

DROP TABLE IF EXISTS "Users";
CREATE TABLE IF NOT EXISTS "Users" (
  id SERIAL PRIMARY KEY NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL
);

-- Companies --

DROP TABLE IF EXISTS "Companies";
CREATE TABLE IF NOT EXISTS "Companies" (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL
);
